// <auto-generated />
namespace webappiProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class partial12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partial12));
        
        string IMigrationMetadata.Id
        {
            get { return "202012241254306_partial12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
